# Generated by Django 5.2.8 on 2026-10-07 08:24
"""Follow accounts.ReceivedEmailMessage.message_id, which this field copies.

`reply_message_id` is assigned straight from a ReceivedEmailMessage.message_id in
accounts/rfq_ai.py and invoices/views.py, and is then emitted as the In-Reply-To
header by invoices/services.py. Once that source became unbounded (see
accounts/migrations/0023), a varchar(255) here would fail on exactly the same
long Microsoft Message-IDs - only later, and in the middle of sending mail.

No data currently exceeds 255 characters in this column, so the change is
preventive rather than a fix for a failed load. EmailDispatchForm does not
include this field, so there is no widget change.

Reversible: yes (AlterField back to CharField), while every stored value still
fits in 255 characters.
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_emaildispatch_reply_message_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaildispatch',
            name='reply_message_id',
            field=models.TextField(blank=True),
        ),
    ]
