# Generated by Django 5.2.8 on 2026-10-07 08:24
"""Make Message-ID unbounded, because RFC 5322 already makes it unbounded.

mailbox_sync copies the inbound `Message-ID` header verbatim. Real values from
Microsoft reach 333 characters:

    '<OneTimePasscode-<guid>;rcid_<guid>;wiid_<guid>@...>'

10 of 427 cached messages in the development database exceeded the previous
varchar(255), which SQLite tolerated and PostgreSQL rejected - so the
SQLite -> PostgreSQL load failed. Any fixed bound here is a production DataError
waiting for the next long header, hence TextField rather than a larger number.
This matches invoices.EmailDispatch.reply_references, which stores the same kind
of value and was already a TextField.

No form or admin view renders this field, so the CharField -> TextField widget
change is not user-visible.

Reversible: yes (AlterField back to CharField), but only while every stored
value fits in 255 characters.
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_user_fe_notes_user_fe_rating_user_invite_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receivedemailmessage',
            name='message_id',
            field=models.TextField(blank=True, verbose_name='Message-ID'),
        ),
    ]
