# Generated by Django 5.2.8 on 2026-10-07 08:24
"""Widen two contact columns that real data already exceeds.

SQLite ignores varchar(n); PostgreSQL enforces it. Loading the development
database into PostgreSQL therefore failed with "value too long for type character
varying(17)" on 25 of 584 Location rows and varying(20) on 27 of 372 CompanyUser
rows. The stored values are legitimate multi-part contact lines, for example:

    '1st Floor(Wom):010-6416 0574/2nd Floor(Men):010-6416 0058'
    'Roger Ye 137 1839 4541// Jingjing Xiu 185 1825 4800'

So the data is right and the columns were too narrow. Neither column is indexed
or unique, and widening a varchar in PostgreSQL is a metadata-only change.

Reversible: yes, AlterField back to the previous max_length - but reversing
*after* long values have been saved will fail on PostgreSQL, which is precisely
the constraint this migration removes.
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0014_company_default_quotation_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyuser',
            name='work_phone',
            field=models.CharField(blank=True, max_length=100, verbose_name='Work Phone'),
        ),
        migrations.AlterField(
            model_name='location',
            name='phone_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Phone Number'),
        ),
    ]
