"""
Django settings for waypost project.

Waypost (驿) - store IT operations platform covering assets, the RFQ -> quotation
-> purchase -> delivery -> invoice chain, and onsite store inspections, with
multi-language support, 2FA, and audit capabilities.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import sys
from datetime import timedelta
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/


def _env_bool(name, default):
    """Parse a boolean environment variable (accepts 1/true/yes/on)."""
    raw = os.environ.get(name)
    if raw is None:
        return default
    return raw.strip().lower() in ('1', 'true', 'yes', 'on')


# True when this process is a test runner rather than a server.
#
# `manage.py test` sets DEBUG=False for the duration of the run, and a
# production-shaped repo-local .env does the same permanently. Either way the
# request-hardening block below would switch on SECURE_SSL_REDIRECT, and since
# the test client makes plain-HTTP requests, every single view test would then
# assert against a 301 instead of the page it asked for.
#
# This only ever relaxes hardening, never a fail-fast guard: the SECRET_KEY,
# FIELD_ENCRYPTION_KEY and WeChat checks above still refuse to boot.
#
# Production cannot trip it. `test` is never in a gunicorn argv, and pytest is
# not installed there - requirements.txt excludes it (requirements-dev.txt has
# it), and the Docker image installs requirements.txt only.
_RUNNING_TESTS = (
    'test' in sys.argv
    or 'pytest' in sys.modules
    or _env_bool('WAYPOST_RUNNING_TESTS', False)
)


# SECURITY WARNING: keep the secret key used in production secret!
# Production MUST set DJANGO_SECRET_KEY (environment or repo-local .env).
# The fallback below is an insecure development-only key.
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-f(g_zcqk%xwx=g3#lnyp=@$c+r%cj=aw8xpr(*=4wc=iwq+!i4',
)

# SECURITY WARNING: don't run with debug turned on in production!
# Defaults to True for local development; production MUST set DJANGO_DEBUG=False.
DEBUG = _env_bool('DJANGO_DEBUG', True)

# Comma-separated host list; defaults to '*' for development convenience.
# Production MUST set DJANGO_ALLOWED_HOSTS to the real domain(s).
ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get('DJANGO_ALLOWED_HOSTS', '*').split(',')
    if host.strip()
]

# Fail fast rather than ship an insecure production configuration:
# when DEBUG is off, the development fallback secret key is not acceptable.
if not DEBUG and SECRET_KEY.startswith('django-insecure-'):
    from django.core.exceptions import ImproperlyConfigured
    raise ImproperlyConfigured(
        'DJANGO_SECRET_KEY must be set to a strong, non-insecure value when '
        'DJANGO_DEBUG is False.'
    )

# ---------------------------------------------------------------------------
# Reverse proxy / TLS termination.
#
# Production runs Gunicorn behind the host Nginx, which terminates TLS and
# forwards `X-Forwarded-Proto: https`. Without SECURE_PROXY_SSL_HEADER Django
# still believes the request is plain HTTP, so `request.is_secure()` is False
# and CsrfViewMiddleware compares the browser's `https://<host>` Origin against
# a rebuilt `http://<host>` - every POST (login included) then fails with 403.
#
# Trusting the header is safe here only because Gunicorn binds to the loopback
# interface and Nginx is the only client that can reach it, so an outsider
# cannot inject `X-Forwarded-Proto` themselves. Off by default: a developer
# running `runserver` directly, or deploying without a proxy, must not have
# Django believe a plain-HTTP request is secure.
# ---------------------------------------------------------------------------
if _env_bool('DJANGO_SECURE_PROXY_SSL_HEADER', False):
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Comma-separated list of origins allowed to make cross-origin POSTs, scheme
# included, e.g. DJANGO_CSRF_TRUSTED_ORIGINS=https://ams.istore-tech.cn
# Needed whenever the public origin differs from what Django can derive from
# the request (proxy, non-standard port, or a subdomain serving the same app).
CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.environ.get('DJANGO_CSRF_TRUSTED_ORIGINS', '').split(',')
    if origin.strip()
]

# Field-level encryption key for credentials stored in the database
# (mailbox / SMTP passwords). Used by accounts/crypto.py (Fernet).
# Production MUST set DJANGO_FIELD_ENCRYPTION_KEY to a Fernet key. Generate one:
#   python -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())"
# Development may omit it; a key is then derived from SECRET_KEY.
FIELD_ENCRYPTION_KEY = os.environ.get('DJANGO_FIELD_ENCRYPTION_KEY', '').strip()

# Fail fast if production would silently fall back to a SECRET_KEY-derived key:
# stored credentials must use a dedicated, explicitly-managed encryption key.
if not DEBUG and not FIELD_ENCRYPTION_KEY:
    from django.core.exceptions import ImproperlyConfigured
    raise ImproperlyConfigured(
        'DJANGO_FIELD_ENCRYPTION_KEY must be set when DJANGO_DEBUG is False. '
        'Generate one with: python -c "from cryptography.fernet import Fernet; '
        'print(Fernet.generate_key().decode())"'
    )

# WeChat mini-program + JWT configuration (Kering store-inspection client).
# The mini program authenticates with SimpleJWT bearer tokens after a WeChat
# jscode2session login. AppSecret is server-side only and MUST be set in production.
WECHAT_MINI_APPID = os.environ.get('WECHAT_MINI_APPID', '').strip()
WECHAT_MINI_APPSECRET = os.environ.get('WECHAT_MINI_APPSECRET', '').strip()
JWT_SIGNING_KEY = os.environ.get('JWT_SIGNING_KEY', '').strip() or SECRET_KEY

# Fail fast if production would run the mini-program backend without WeChat creds:
# jscode2session cannot work and openid binding would silently fail.
if not DEBUG and (not WECHAT_MINI_APPID or not WECHAT_MINI_APPSECRET):
    from django.core.exceptions import ImproperlyConfigured
    raise ImproperlyConfigured(
        'WECHAT_MINI_APPID and WECHAT_MINI_APPSECRET must be set when '
        'DJANGO_DEBUG is False.'
    )

MINIMAX_TOKEN_PLAN_KEY = os.environ.get('minimax_token_plan_key', '')
MINIMAX_RFQ_API_URL = os.environ.get('MINIMAX_RFQ_API_URL', 'https://api.minimaxi.com/anthropic/v1/messages')
MINIMAX_RFQ_MODEL = os.environ.get('MINIMAX_RFQ_MODEL', 'MiniMax-M2.7-highspeed')
MINIMAX_RFQ_TIMEOUT_SECONDS = float(os.environ.get('MINIMAX_RFQ_TIMEOUT_SECONDS', '30'))
MINIMAX_RFQ_MAX_TOKENS = int(os.environ.get('MINIMAX_RFQ_MAX_TOKENS', '800'))
TEST_OUTBOUND_EMAIL_OVERRIDE = os.environ.get('TEST_OUTBOUND_EMAIL_OVERRIDE', 'sean.liu@istore-tech.com').strip()

# ---------------------------------------------------------------------------
# Branding. Three distinct names - do NOT collapse them into one.
#
#   PRODUCT_*    The product brand (renamed 2026-10, was "HengJi AMS"). Never
#                translated: templates render the literal "Waypost" and only
#                PRODUCT_TAGLINE is localised.
#   COMPANY_*    The contracting / seller entity. It owns the assets and signs
#                the quotation and delivery-note PDFs that go to customers.
#                Unchanged by the product rebrand.
#   PUBLISHER_*  The publishing entity. Used for copyright notices, the web
#                footer, LICENSE and documentation contact details.
#
# Everything emitted from Python MUST read these instead of hardcoding a string:
# the old brand had already drifted between OTP_TOTP_ISSUER and accounts/views.py.
# The web footer and LICENSE carry PUBLISHER_NAME_* as literals (templates cannot
# read settings without a context processor); keep them in step by hand.
# ---------------------------------------------------------------------------
PRODUCT_NAME = 'Waypost'
PRODUCT_NAME_ZH = '驿'
PRODUCT_TAGLINE = 'From RFQ to the shop floor'

COMPANY_NAME_EN = 'HengJi'
COMPANY_NAME_ZH = '上海珩际信息科技有限公司'

PUBLISHER_NAME_EN = 'iStore Tech'
PUBLISHER_NAME_ZH = '上海思导信息科技有限公司'


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third-party apps
    'django_extensions',  # Provides useful extensions for Django development
    'django_otp',  # Two-factor authentication support
    'django_otp.plugins.otp_totp',  # TOTP (Time-based OTP) support
    'django_otp.plugins.otp_static',  # Static OTP tokens for backup
    'rest_framework',  # REST API framework
    'rest_framework_simplejwt',  # JWT auth for the WeChat mini program
    # Local apps
    'accounts',  # Custom user management with roles and 2FA
    'assets',  # Asset management core functionality
    'companies',  # Company and division management
    'inspections',  # Kering store device-inspection (WeChat mini program backend)
    'reports',  # Reporting and analytics
    'dashboard',  # Main dashboard and overview
    'users',  # User management
    'api',  # REST API
    'mobile',  # Mobile interface
    'products',  # Product price list
    'customers',  # Customer profiles
    'quotations',  # Quotation management
    'purchases',  # Purchase and stock management
    'deliveries',  # Delivery order management
    'invoices',  # Weekly sharepoint processing and invoice staging
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',  # For internationalization
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django_otp.middleware.OTPMiddleware',  # For 2FA support
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# WhiteNoise serves static files in production. It must sit directly after
# SecurityMiddleware. Guarded by DEBUG so local development does not require
# the package to be installed (dev uses runserver's own static handling).
if not DEBUG:
    MIDDLEWARE.insert(1, 'whitenoise.middleware.WhiteNoiseMiddleware')

ROOT_URLCONF = 'waypost.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # Global templates directory
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.i18n',  # For internationalization
                'dashboard.context_processors.pending_tasks',
            ],
        },
    },
]

WSGI_APPLICATION = 'waypost.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
#
# Defaults to SQLite for local development. For PostgreSQL (production), set
# these in the environment or repo-local .env:
#   DATABASE_ENGINE=django.db.backends.postgresql
#   DATABASE_NAME=waypost_db
#   DATABASE_USER=waypost_django
#   DATABASE_PASSWORD=<secret>
#   DATABASE_HOST=127.0.0.1
#   DATABASE_PORT=5432
# SQLite ignores USER/PASSWORD/HOST/PORT, so the empty defaults are safe.
DATABASES = {
    'default': {
        'ENGINE': os.environ.get('DATABASE_ENGINE', 'django.db.backends.sqlite3'),
        'NAME': os.environ.get('DATABASE_NAME', str(BASE_DIR / 'db.sqlite3')),
        'USER': os.environ.get('DATABASE_USER', ''),
        'PASSWORD': os.environ.get('DATABASE_PASSWORD', ''),
        'HOST': os.environ.get('DATABASE_HOST', ''),
        'PORT': os.environ.get('DATABASE_PORT', ''),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Django REST Framework configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
}

# SimpleJWT (mini-program bearer tokens). Access tokens are short-lived; refresh
# tokens let the offline-first client re-auth without re-prompting credentials.
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=int(os.environ.get('JWT_ACCESS_HOURS', '2'))),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=int(os.environ.get('JWT_REFRESH_DAYS', '14'))),
    'SIGNING_KEY': JWT_SIGNING_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'ROTATE_REFRESH_TOKENS': False,
    'UPDATE_LAST_LOGIN': True,
}


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

# List of supported languages
LANGUAGES = [
    ('en-us', 'English (US)'),
    ('zh-cn', 'Simplified Chinese'),
]

# Directory containing translation files
LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Static files storage (Django 5.x STORAGES API).
# Production: WhiteNoise's CompressedManifestStaticFilesStorage - hashed
#   filenames for cache-busting plus pre-compressed .gz/.br. Nginx serves the
#   collected files directly (fast path); WhiteNoise is the in-app fallback.
# Development: plain StaticFilesStorage so `collectstatic`/manifest is not
#   required locally and the whitenoise package need not be installed.
STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': (
            'whitenoise.storage.CompressedManifestStaticFilesStorage'
            if not DEBUG
            else 'django.contrib.staticfiles.storage.StaticFilesStorage'
        ),
    },
}

# Media files (user uploads) - served by Nginx in production.
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Cache backend.
# Production: Redis via django-redis when DJANGO_REDIS_CACHE_URL is set
#   (e.g. redis://127.0.0.1:6379/1).
# Development: local-memory cache - no Redis server or extra package required.
_redis_cache_url = os.environ.get('DJANGO_REDIS_CACHE_URL', '').strip()
if _redis_cache_url:
    CACHES = {
        'default': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': _redis_cache_url,
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            },
            'KEY_PREFIX': 'waypost',
        }
    }
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'waypost-dev',
        }
    }

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Authentication settings
AUTH_USER_MODEL = 'accounts.User'  # Custom user model

# Login/Logout URLs
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/login/'

# Two-Factor Authentication settings
OTP_TOTP_ISSUER = PRODUCT_NAME
OTP_LOGIN_URL = '/login/'

# Session settings
SESSION_COOKIE_AGE = 86400  # 24 hours
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# Security settings for production
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'

if not DEBUG and not _RUNNING_TESTS:
    # Cookie/redirect hardening. Gated on DEBUG so local http://127.0.0.1
    # development is unaffected - a secure cookie over plain HTTP is simply
    # never sent back, which presents as "login does nothing".
    SESSION_COOKIE_SECURE = _env_bool('DJANGO_SESSION_COOKIE_SECURE', True)
    CSRF_COOKIE_SECURE = _env_bool('DJANGO_CSRF_COOKIE_SECURE', True)
    SECURE_SSL_REDIRECT = _env_bool('DJANGO_SECURE_SSL_REDIRECT', True)

    # HSTS is sticky: a browser caches the header for the whole max-age and
    # cannot be told to forget it, so a mistake here pins the domain to HTTPS
    # for months. Ships disabled (0) and is raised via the environment only
    # after HTTPS has been verified in production (31536000 = one year).
    SECURE_HSTS_SECONDS = int(os.environ.get('DJANGO_SECURE_HSTS_SECONDS', '0'))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = _env_bool('DJANGO_HSTS_INCLUDE_SUBDOMAINS', False)
    SECURE_HSTS_PRELOAD = _env_bool('DJANGO_HSTS_PRELOAD', False)

# The health probe must stay reachable over plain HTTP: the container
# healthcheck and the deploy script's loopback poll talk to Gunicorn directly,
# with no proxy in front to set X-Forwarded-Proto. Exempting the path keeps
# SECURE_SSL_REDIRECT on for every real request.
SECURE_REDIRECT_EXEMPT = [r'^healthz/$']

# Asset management specific settings
ASSET_PHOTO_UPLOAD_PATH = 'assets/photos/'
ASSET_BARCODE_UPLOAD_PATH = 'assets/barcodes/'
MAX_UPLOAD_SIZE = 5242880  # 5MB

# Email settings (for notifications)
EMAIL_BACKEND = 'accounts.email_backends.DatabaseSMTPEmailBackend'
DEFAULT_FROM_EMAIL = ''

# Logging configuration
# The log directory is gitignored, so bootstrap it here: logging.FileHandler
# does not create parent directories, and django.setup() would otherwise fail
# on any fresh checkout (CI, a new clone, or a first production deploy).
LOG_DIR = BASE_DIR / 'logs'
LOG_DIR.mkdir(parents=True, exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'INFO',
            # Rotating rather than plain: under a container the log file lives
            # in the writable layer, so an unbounded FileHandler grows that
            # layer forever. 10 MB x 5 caps history at ~50 MB.
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOG_DIR / 'waypost.log',
            'maxBytes': 10 * 1024 * 1024,
            'backupCount': 5,
            'encoding': 'utf-8',
        },
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': True,
        },
        'assets': {
            'handlers': ['file', 'console'],
            'level': 'DEBUG',
            'propagate': True,
        },
    },
}
